name: CI
on:
  pull_request:
jobs:
  build-and-test:
    name: Build and Test
    uses: access-nri/build-ci/.github/workflows/ci.yml@build-ci-2.0
    with:
      # This is the only required input - a path to a jinja-template-able Spack Environment file.
      spack-manifest-path: .github/build-ci/templates/basic.spack.yaml.j2
      ## But there are many other things you can customize...
      ## Like the refs that you want to use for the various repos (including this one).
      # ref: github.sha of this repository
      # spack-config-ref: whatever was in the image
      # spack-packages-ref: whatever was in the image
      # spack-ref: whatever was in the image

      ## As well as paths to other spack.yaml files for installation of compilers and template values
      # spack-compiler-manifest-path: ''
      # spack-manifest-data-path: ''

      ## Or allow ssh into the container for debugging
      # allow-ssh-into-spack-install: false
